version: '3.8'
services: 
  db:
    image: postgres:13.10
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: todo
    ports:
      - 5431:5432
    volumes:
      - ./init-scripts:/docker-entrypoint-initdb.d

    
 